name = "stdlib_test"
version = "0.1.0"
license = "license"
author = "Oscar Garcia-Cabrejo"
maintainer = "khaors@gmail.com"
copyright = "Copyright 2024, khaors"
[dependencies]
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

